const { DataTypes } = require("sequelize");

const AltBeatmapLiveModel = (db) => db.define('BeatmapLive', {
    beatmap_id: { type: DataTypes.INTEGER, primaryKey: true },
    mapper_id: { type: DataTypes.INTEGER },
    beatmapset_id: { type: DataTypes.INTEGER },
    mode: { type: DataTypes.INTEGER },
    status: { type: DataTypes.INTEGER },
    stars: { type: DataTypes.FLOAT },
    od: { type: DataTypes.FLOAT },
    ar: { type: DataTypes.FLOAT },
    bpm: { type: DataTypes.FLOAT },
    cs: { type: DataTypes.FLOAT },
    hp: { type: DataTypes.FLOAT },
    length: { type: DataTypes.INTEGER },
    drain_time: { type: DataTypes.INTEGER },
    count_circles: { type: DataTypes.INTEGER },
    count_sliders: { type: DataTypes.INTEGER },
    count_spinners: { type: DataTypes.INTEGER },
    max_combo: { type: DataTypes.INTEGER },
    pass_count: { type: DataTypes.INTEGER },
    play_count: { type: DataTypes.INTEGER },
    fc_count: { type: DataTypes.INTEGER },
    ss_count: { type: DataTypes.INTEGER },
    favourite_count: { type: DataTypes.INTEGER },
    ranked_date: { type: DataTypes.DATE },
    submitted_date: { type: DataTypes.DATE },
    last_updated: { type: DataTypes.DATE },
    version: { type: DataTypes.STRING },
    title: { type: DataTypes.STRING },
    artist: { type: DataTypes.STRING },
    source: { type: DataTypes.STRING },
    tags: { type: DataTypes.TEXT },
    checksum: { type: DataTypes.STRING },
    track_id: { type: DataTypes.INTEGER },
    pack: { type: DataTypes.STRING },
    lchg_time: { type: DataTypes.DATE },
    mapper: { type: DataTypes.STRING },
    is_nsfw: { type: DataTypes.BOOLEAN },
    beatmap_offset: { type: DataTypes.INTEGER },
    rating: { type: DataTypes.FLOAT },
    is_spotlight: { type: DataTypes.BOOLEAN },
    genre: { type: DataTypes.INTEGER },
    language: { type: DataTypes.INTEGER },
    has_video: { type: DataTypes.BOOLEAN },
    has_storyboard: { type: DataTypes.BOOLEAN },
    download_disabled: { type: DataTypes.BOOLEAN },
    mode_str: { type: DataTypes.STRING },
    is_convert: { type: DataTypes.BOOLEAN },
    current_user_playcount: { type: DataTypes.INTEGER },
    beatmap_deleted_at: { type: DataTypes.DATE },
    beatmap_is_scoreable: { type: DataTypes.BOOLEAN },
    ranked_raw: { type: DataTypes.INTEGER },
    url: { type: DataTypes.STRING },
    //jsonb
    owners: { type: DataTypes.JSONB }
}, {
    tableName: 'beatmapfull',
    timestamps: false
});

module.exports = AltBeatmapLiveModel;