const { DataTypes } = require("sequelize");

const AltScoreLiveModel = (db) => db.define('ScoreLive', {
    id: { type: DataTypes.BIGINT, primaryKey: true },
    beatmap_id: { type: DataTypes.BIGINT, field: 'beatmap_id_fk' },
    user_id: { type: DataTypes.BIGINT, field: 'user_id_fk' },
    accuracy: { type: DataTypes.FLOAT },
    best_id: { type: DataTypes.BIGINT },
    build_id: { type: DataTypes.INTEGER },
    classic_total_score: { type: DataTypes.BIGINT },
    ended_at: { type: DataTypes.DATE },
    has_replay: { type: DataTypes.BOOLEAN },
    is_perfect_combo: { type: DataTypes.BOOLEAN },
    legacy_perfect: { type: DataTypes.BOOLEAN },
    legacy_score_id: { type: DataTypes.BIGINT },
    legacy_total_score: { type: DataTypes.BIGINT },
    combo: { type: DataTypes.INTEGER },
    maximum_statistics_perfect: { type: DataTypes.INTEGER },
    maximum_statistics_great: { type: DataTypes.INTEGER },
    maximum_statistics_miss: { type: DataTypes.INTEGER },
    maximum_statistics_ignore_hit: { type: DataTypes.INTEGER },
    maximum_statistics_ignore_miss: { type: DataTypes.INTEGER },
    maximum_statistics_slider_tail_hit: { type: DataTypes.INTEGER },
    maximum_statistics_legacy_combo_increase: { type: DataTypes.INTEGER },
    maximum_statistics_large_bonus: { type: DataTypes.INTEGER },
    maximum_statistics_large_tick_hit: { type: DataTypes.INTEGER },
    maximum_statistics_small_bonus: { type: DataTypes.INTEGER },
    maximum_statistics_small_tick_hit: { type: DataTypes.INTEGER },
    mods: { type: DataTypes.INTEGER },
    passed: { type: DataTypes.BOOLEAN },
    pp: { type: DataTypes.FLOAT },
    preserve: { type: DataTypes.BOOLEAN },
    processed: { type: DataTypes.BOOLEAN },
    grade: { type: DataTypes.STRING },
    ranked: { type: DataTypes.INTEGER },
    replay: { type: DataTypes.BOOLEAN },
    ruleset_id: { type: DataTypes.INTEGER },
    started_at: { type: DataTypes.DATE },
    statistics_perfect: { type: DataTypes.INTEGER },
    statistics_great: { type: DataTypes.INTEGER },
    statistics_good: { type: DataTypes.INTEGER },
    statistics_ok: { type: DataTypes.INTEGER },
    statistics_meh: { type: DataTypes.INTEGER },
    statistics_miss: { type: DataTypes.INTEGER },
    statistics_ignore_hit: { type: DataTypes.INTEGER },
    statistics_ignore_miss: { type: DataTypes.INTEGER },
    statistics_slider_tail_hit: { type: DataTypes.INTEGER },
    statistics_slider_tail_miss: { type: DataTypes.INTEGER },
    statistics_large_bonus: { type: DataTypes.INTEGER },
    statistics_large_tick_hit: { type: DataTypes.INTEGER },
    statistics_large_tick_miss: { type: DataTypes.INTEGER },
    statistics_small_bonus: { type: DataTypes.INTEGER },
    statistics_small_tick_hit: { type: DataTypes.INTEGER },
    statistics_small_tick_miss: { type: DataTypes.INTEGER },
    statistics_combo_break: { type: DataTypes.INTEGER },
    total_score: { type: DataTypes.BIGINT },
    total_score_without_mods: { type: DataTypes.BIGINT },
    type: { type: DataTypes.STRING },
    highest_score: { type: DataTypes.BOOLEAN },
    highest_pp: { type: DataTypes.BOOLEAN },
    rank: { type: DataTypes.INTEGER },
    mod_acronyms: { type: DataTypes.STRING },
    mod_speed_change: { type: DataTypes.FLOAT },
    difficulty_reducing: { type: DataTypes.BOOLEAN },
    difficulty_removing: { type: DataTypes.BOOLEAN },
    lchg_time: { type: DataTypes.DATE },
    attr_diff: { type: DataTypes.JSON },
    attr_date: { type: DataTypes.DATE },
    attr_recalc: { type: DataTypes.BOOLEAN },
    is_ss: { type: DataTypes.BOOLEAN },
    is_fc: { type: DataTypes.BOOLEAN }
}, {
    tableName: 'scorelive',
    timestamps: false
});

module.exports = AltScoreLiveModel;